name: Build on tag and push to CurseForge

on:
  push:
    tags:
      - 'v?\d.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Build
        run: chmod 777 gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Push to CurseForge
        run: ./gradlew curseforge

      - name: Publish to Maven
        run: ./gradlew publish